# Generated by Django 4.1.5 on 2023-01-18 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('description', models.TextField(db_column='description')),
                ('duration', models.FloatField(db_column='duration')),
                ('release_year', models.IntegerField(db_column='year',
                                                     validators=[django.core.validators.MinValueValidator(1900),
                                                                 django.core.validators.MaxValueValidator(2050)])),
                ('pic_url', models.URLField(db_column='url', max_length=512, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
