# Generated by Django 4.1.5 on 2023-01-23 20:28
import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(db_column='date', default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(db_column='text')),
                ('review_date', models.DateField(db_column='date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.movie')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
