# Generated by Django 4.1.5 on 2023-01-29 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(db_column='release_year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(db_column='rating_date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(db_column='review_date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(db_column='review_text'),
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('main_role', models.BooleanField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie')),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='movies_app.MovieActor', to='movies_app.actor'),
        ),
    ]
